### Continuous Deployment: Build & Deploy mit Docker Compose

name: CD Pipeline

on:
  push:
    branches:
      - UAT
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Build & Push Backend Image
        run: |
          docker build -t myrepo/backend:${{ github.ref_name }} -f backend/Dockerfile .
          docker push myrepo/backend:${{ github.ref_name }}
      
      - name: Build & Push Frontend Image
        run: |
          docker build -t myrepo/frontend:${{ github.ref_name }} -f frontend/Dockerfile .
          docker push myrepo/frontend:${{ github.ref_name }}
      
      - name: Build & Push MLflow Image
        run: |
          docker build -t myrepo/mlflow:${{ github.ref_name }} -f mlflow/Dockerfile .
          docker push myrepo/mlflow:${{ github.ref_name }}

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: SSH into Server & Deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/deploy/myproject
            git pull origin main
            docker-compose down
            docker-compose pull
            docker-compose up -d